services:
  nfc-handler:
    build:
      context: .
      dockerfile: Dockerfile
      target: nfc-handler
    ports:
      - "8081:443"
    restart: unless-stopped

  nfc-reader:
    build:
      context: .
      dockerfile: Dockerfile
      target: nfc-reader
    ports:
      - "8082:443"
    restart: unless-stopped
